In [385]:
import pandas as pd

df = pd.read_csv("../data/raw/INvideos.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 37352
Columns: 16

In [386]:
print(df["video_id"].head(10))
print("Unique video IDs:", df["video_id"].nunique())

0    kzwfHumJyYc
1    zUZ1z7FwLc8
2    10L1hZ9qa58
3    N1vE8iiEg64
4    kJzGH0PVQHQ
5    il_pSa5l98w
6    7MxiQ4v0EnE
7    c64I9HNpiOY
8    KObFEYCaRx8
9    g8QsfJhFpjY
Name: video_id, dtype: str
Unique video IDs: 16307

In [387]:
clean_df = df.copy()

In [388]:
duplicate_count = clean_df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 4263

In [389]:
clean_df = clean_df.drop_duplicates().reset_index(drop=True)

In [390]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [391]:
numeric_columns = [
    "views",
    "likes",
    "dislikes",
    "comment_count"
]

In [392]:
for column in numeric_columns:
    clean_df[column] = pd.to_numeric(
        clean_df[column],
        errors="coerce"
    )

In [393]:
clean_df["trending_date"] = pd.to_datetime(
    clean_df["trending_date"],
    format="%y.%d.%m",
    errors="coerce"
)

In [394]:
clean_df["publish_time"] = pd.to_datetime(
    clean_df["publish_time"],
    errors="coerce",
    utc=True
)

In [395]:
print(
    "Invalid trending dates:",
    clean_df["trending_date"].isna().sum()
)

print(
    "Invalid publish times:",
    clean_df["publish_time"].isna().sum()
)

Invalid trending dates: 0
Invalid publish times: 0

In [396]:
missing_values = clean_df.isna().sum()

print(
    missing_values[missing_values > 0]
)

description    527
dtype: int64

In [397]:
print("Negative views:",
      (clean_df["views"] < 0).sum())

print("Negative likes:",
      (clean_df["likes"] < 0).sum())

print("Negative dislikes:",
      (clean_df["dislikes"] < 0).sum())

print("Negative comments:",
      (clean_df["comment_count"] < 0).sum())

Negative views: 0
Negative likes: 0
Negative dislikes: 0
Negative comments: 0

In [398]:
clean_df["publish_date"] = (
    clean_df["publish_time"]
    .dt.tz_localize(None)
    .dt.normalize()
)

In [399]:
clean_df["time_to_trend_days"] = (
    clean_df["trending_date"]
    - clean_df["publish_date"]
).dt.days

In [400]:
print(
    "Negative Time-to-Trend:",
    (clean_df["time_to_trend_days"] < 0).sum()
)

Negative Time-to-Trend: 0

In [401]:
clean_df = clean_df[
    clean_df["views"] >= 0
].copy()

In [402]:
print(clean_df.shape)

(33089, 18)

In [403]:
clean_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,publish_date,time_to_trend_days
0,kzwfHumJyYc,2017-11-14,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...,2017-11-12,2
1,zUZ1z7FwLc8,2017-11-14,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13 05:43:56+00:00,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",2017-11-13,1
2,10L1hZ9qa58,2017-11-14,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12 15:48:08+00:00,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...,2017-11-12,2
3,N1vE8iiEg64,2017-11-14,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12 07:08:48+00:00,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...,2017-11-12,2
4,kJzGH0PVQHQ,2017-11-14,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13 01:14:16+00:00,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...,2017-11-13,1

In [404]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33089 entries, 0 to 33088
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                33089 non-null  str
 1   trending_date           33089 non-null  datetime64[us]
 2   title                   33089 non-null  str
 3   channel_title           33089 non-null  str
 4   category_id             33089 non-null  int64
 5   publish_time            33089 non-null  datetime64[us, UTC]
 6   tags                    33089 non-null  str
 7   views                   33089 non-null  int64
 8   likes                   33089 non-null  int64
 9   dislikes                33089 non-null  int64
 10  comment_count           33089 non-null  int64
 11  thumbnail_link          33089 non-null  str
 12  comments_disabled       33089 non-null  bool
 13  ratings_disabled        33089 non-null  bool
 14  video_error_or_removed  33089 non-null  bool
 15  description             32562 non-null  str
 16  publish_date            33089 non-null  datetime64[us]
 17  time_to_trend_days      33089 non-null  int64
dtypes: bool(3), datetime64[us, UTC](1), datetime64[us](2), int64(6), str(6)
memory usage: 3.9 MB

In [405]:
print("Rows:", len(clean_df))

print(
    "Unique videos:",
    clean_df["video_id"].nunique()
)

print(
    "Duplicate rows:",
    clean_df.duplicated().sum()
)

print(
    "Missing video IDs:",
    clean_df["video_id"].isna().sum()
)

Rows: 33089
Unique videos: 16307
Duplicate rows: 0
Missing video IDs: 0

In [406]:
import os

os.makedirs(
    "../data/processed",
    exist_ok=True
)

In [407]:
clean_df.to_csv(
    "../data/processed/youtube_cleaned.csv",
    index=False
)

In [408]:
import sqlite3

db_path = "../data/youtube_trendpulse.db"

conn = sqlite3.connect(db_path)

print("Database connected successfully!")

Database connected successfully!

In [409]:
clean_df.to_sql(
    "youtube_trends",
    conn,
    if_exists="replace",
    index=False
)

print("Data loaded into SQL successfully!")

Data loaded into SQL successfully!

In [410]:
query = """
SELECT COUNT(*) AS total_rows
FROM youtube_trends
"""

result = pd.read_sql_query(query, conn)

print(result)

   total_rows
0       33089

In [411]:
query = """
SELECT *
FROM youtube_trends
LIMIT 10
"""

sql_preview = pd.read_sql_query(query, conn)

sql_preview

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,publish_date,time_to_trend_days
0,kzwfHumJyYc,2017-11-14 00:00:00,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12 12:20:39+00:00,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,0,0,0,Presenting Sharry Mann latest Punjabi Song Cu...,2017-11-12 00:00:00,2
1,zUZ1z7FwLc8,2017-11-14 00:00:00,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13 05:43:56+00:00,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,1,0,0,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",2017-11-13 00:00:00,1
2,10L1hZ9qa58,2017-11-14 00:00:00,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12 15:48:08+00:00,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,0,0,0,Watch Stylish Star Allu Arjun @ ChaySam Weddin...,2017-11-12 00:00:00,2
3,N1vE8iiEg64,2017-11-14 00:00:00,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12 07:08:48+00:00,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,0,0,0,This video showcases the difference between pe...,2017-11-12 00:00:00,2
4,kJzGH0PVQHQ,2017-11-14 00:00:00,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13 01:14:16+00:00,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,0,0,0,why Samantha became EMOTIONAL @ Samantha naga ...,2017-11-13 00:00:00,1
5,il_pSa5l98w,2017-11-14 00:00:00,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10 04:29:50+00:00,"Nenu Local|""Nenu Local Telugu Movie""|""Nani""|""S...",6106669,98612,4185,4763,https://i.ytimg.com/vi/il_pSa5l98w/default.jpg,0,0,0,Watch MCA- Middle Class Abbayi First Look Teas...,2017-11-10 00:00:00,4
6,7MxiQ4v0EnE,2017-11-14 00:00:00,Daang ( Full Video ) | Mankirt Aulakh | Sukh S...,Speed Records,10,2017-11-11 16:41:15+00:00,"punjabi songs|""punjabi bhangra""|""punjabi music...",5718766,127477,7134,8063,https://i.ytimg.com/vi/7MxiQ4v0EnE/default.jpg,0,0,0,Song - Daang\nSinger - Mankirt Aulakh\nFaceboo...,2017-11-11 00:00:00,3
7,c64I9HNpiOY,2017-11-14 00:00:00,Padmavati : Ek Dil Ek Jaan Video Song | Deepik...,T-Series,10,2017-11-11 06:14:19+00:00,"Ek Dil Ek Jaan Video Song|""'Ek Dil Ek Jaan'""|""...",10588371,132738,8812,10847,https://i.ytimg.com/vi/c64I9HNpiOY/default.jpg,0,0,0,Presenting the song 'Ek Dil Ek Jaan' from Padm...,2017-11-11 00:00:00,3
8,KObFEYCaRx8,2017-11-14 00:00:00,Chiranjeevi in Naga Chaitanya - Samantha Recep...,Top Telugu Media,24,2017-11-13 04:42:26+00:00,Chiranjeevi in Naga Chaitanya - Samantha Recep...,118223,520,53,23,https://i.ytimg.com/vi/KObFEYCaRx8/default.jpg,0,0,0,Chiranjeevi in Naga Chaitanya - Samantha Recep...,2017-11-13 00:00:00,1
9,g8QsfJhFpjY,2017-11-14 00:00:00,New bike vs Old bike - the reality,Jump Cuts,24,2017-11-12 04:30:01+00:00,"Jump cuts|""Jumpcuts""|""Tamil comedy""|""Tamil Com...",969030,59798,1545,2404,https://i.ytimg.com/vi/g8QsfJhFpjY/default.jpg,0,0,0,Jump Cuts is a Tamil entertaining group by Har...,2017-11-12 00:00:00,2

In [412]:
query = """
SELECT
    video_id,
    title,
    channel_title,
    views,
    likes,
    comment_count
FROM youtube_trends
ORDER BY views DESC
LIMIT 10
"""

top_videos = pd.read_sql_query(query, conn)

top_videos

,video_id,title,channel_title,views,likes,comment_count
0,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,125432237,2912710,807558
1,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,113876217,2811216,787174
2,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,100911567,2656672,682890
3,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,89930713,2606663,347982
4,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,87449453,2584674,341571
5,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,84281319,2555411,339708
6,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,80360459,2513102,335920
7,FlsCjmMhFmw,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,75969469,2251815,827755
8,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,74789251,2444956,330710
9,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,66637636,2331352,316185

In [413]:
query = """
CREATE VIEW IF NOT EXISTS daily_youtube_metrics AS

SELECT
    trending_date,
    COUNT(DISTINCT video_id) AS unique_videos,
    SUM(views) AS total_views,
    SUM(likes) AS total_likes,
    SUM(comment_count) AS total_comments,
    AVG(views) AS average_views

FROM youtube_trends

GROUP BY trending_date

ORDER BY trending_date
"""

conn.execute(query)
conn.commit()

In [414]:
query = """
SELECT *
FROM daily_youtube_metrics
LIMIT 10
"""

daily_metrics = pd.read_sql_query(query, conn)

daily_metrics

,trending_date,unique_videos,total_views,total_likes,total_comments,average_views
0,2017-11-14 00:00:00,198,156925939,4285551,357375,7.846297e+05
1,2017-11-15 00:00:00,199,181630109,4613549,448854,9.081505e+05
2,2017-11-16 00:00:00,198,153104025,2999706,389193,7.655201e+05
3,2017-11-17 00:00:00,200,114034530,2243816,291825,5.701727e+05
4,2017-11-18 00:00:00,197,105291667,2327084,355222,5.264583e+05
5,2017-11-19 00:00:00,199,115818437,2771232,389370,5.790922e+05
6,2017-11-20 00:00:00,198,120906446,2619317,385383,6.106386e+05
7,2017-11-21 00:00:00,171,127635271,2617209,257676,7.293444e+05
8,2017-11-22 00:00:00,113,144778846,2690840,257704,1.226939e+06
9,2017-11-23 00:00:00,184,156746121,3166190,287989,8.382146e+05

In [415]:
query = """
CREATE VIEW IF NOT EXISTS category_performance AS

SELECT
    category_id,
    COUNT(DISTINCT video_id) AS unique_videos,
    SUM(views) AS total_views,
    SUM(likes) AS total_likes,
    SUM(comment_count) AS total_comments,
    AVG(views) AS average_views

FROM youtube_trends

GROUP BY category_id

ORDER BY total_views DESC
"""

conn.execute(query)
conn.commit()

In [416]:
query = """
SELECT *
FROM category_performance
"""

category_data = pd.read_sql_query(query, conn)

category_data

,category_id,unique_videos,total_views,total_likes,total_comments,average_views
0,24,7564,13326399551,328229550,35486403,9.026280e+05
1,10,1216,8336504205,213063323,14558095,2.532352e+06
2,1,523,3273144924,57790703,4844060,2.237283e+06
3,23,1117,2423485988,146425199,11560689,8.168136e+05
4,25,2507,1658578208,13449502,2535027,3.522145e+05
5,17,348,1192613734,28473825,2346624,1.846151e+06
6,22,1234,1146217515,19883239,2331943,4.842491e+05
7,26,480,674464823,7247108,693467,8.420285e+05
8,28,302,435729557,18121097,7580486,8.428038e+05
9,20,21,198350285,5100129,485860,3.606369e+06
10,27,799,132322235,6843999,874977,1.134839e+05
11,43,122,99079954,547324,77939,6.649661e+05
12,30,2,31919530,409750,22962,3.191953e+06
13,2,34,26439304,488917,86488,3.831783e+05
14,29,69,6473302,215655,12844,6.284759e+04
15,15,2,4879743,362534,42056,1.626581e+06
16,19,4,1374342,16939,2448,1.717928e+05

In [417]:
query = """
CREATE VIEW IF NOT EXISTS video_engagement AS

SELECT
    video_id,
    title,
    channel_title,
    trending_date,
    views,
    likes,
    comment_count,

    (
        (likes + comment_count) * 100.0
        / NULLIF(views, 0)
    ) AS engagement_rate

FROM youtube_trends
"""

conn.execute(query)
conn.commit()

In [418]:
query = """
SELECT
    video_id,
    title,
    channel_title,
    views,
    engagement_rate

FROM video_engagement

ORDER BY engagement_rate DESC

LIMIT 10
"""

engagement_data = pd.read_sql_query(query, conn)

engagement_data

,video_id,title,channel_title,views,engagement_rate
0,TyYV_h2bXM0,OnePlus 6 Top Features and GIVEAWAY 🔥- OnePlus...,Technical Guruji,840727,77.428226
1,uKmx6OnbuN0,Oneplus 5T Lava Red Unboxing and Giveaway 🔥🔥🔥 ...,Technical Guruji,335058,68.932841
2,TyYV_h2bXM0,OnePlus 6 Top Features and GIVEAWAY 🔥- OnePlus...,Technical Guruji,1049339,68.877741
3,TyYV_h2bXM0,OnePlus 6 Top Features and GIVEAWAY 🔥- OnePlus...,Technical Guruji,1158291,65.028391
4,1hHvH8xQDKA,OnePlus 5T Star Wars Limited Edition Unboxing ...,Technical Guruji,446587,62.691928
5,GqCAVnvb3QA,Samsung Galaxy S9 Top Features and Tips Tricks...,Technical Guruji,921731,59.425255
6,uKmx6OnbuN0,Oneplus 5T Lava Red Unboxing and Giveaway 🔥🔥🔥 ...,Technical Guruji,446879,56.051191
7,1hHvH8xQDKA,OnePlus 5T Star Wars Limited Edition Unboxing ...,Technical Guruji,559686,55.542215
8,1hHvH8xQDKA,OnePlus 5T Star Wars Limited Edition Unboxing ...,Technical Guruji,611786,53.318971
9,Nx6ee-vSPc0,Xiaomi Redmi 5A Unboxing & initial impressions...,Prasadtechintelugu,60209,49.705194

In [419]:
query = """
SELECT name
FROM sqlite_master
WHERE type IN ('table', 'view')
"""

objects = pd.read_sql_query(query, conn)

objects

                     name
0  daily_business_metrics
1          youtube_videos
2   daily_youtube_metrics
3    category_performance
4        video_engagement
5          trend_velocity
6         emerging_trends
7          youtube_trends

In [420]:
conn.commit()
conn.close()

print("SQL database saved successfully!")

SQL database saved successfully!

In [421]:
raw_df = pd.read_csv("../data/raw/INvideos.csv")

print(raw_df["video_id"].head(10))
print("Unique video IDs:", raw_df["video_id"].nunique())

0    kzwfHumJyYc
1    zUZ1z7FwLc8
2    10L1hZ9qa58
3    N1vE8iiEg64
4    kJzGH0PVQHQ
5    il_pSa5l98w
6    7MxiQ4v0EnE
7    c64I9HNpiOY
8    KObFEYCaRx8
9    g8QsfJhFpjY
Name: video_id, dtype: str
Unique video IDs: 16307

In [422]:
velocity_df = raw_df[
    ["video_id", "trending_date", "views", "likes", "comment_count"]
].copy()

In [423]:
for col in ["views", "likes", "comment_count"]:
    velocity_df[col] = pd.to_numeric(
        velocity_df[col],
        errors="coerce"
    )

In [424]:
velocity_df = velocity_df[
    velocity_df["video_id"] != "#NAME?"
].copy()

In [425]:
velocity_df = velocity_df.reset_index(drop=True)

In [426]:
print(velocity_df["video_id"].head(20))

0     kzwfHumJyYc
1     zUZ1z7FwLc8
2     10L1hZ9qa58
3     N1vE8iiEg64
4     kJzGH0PVQHQ
5     il_pSa5l98w
6     7MxiQ4v0EnE
7     c64I9HNpiOY
8     KObFEYCaRx8
9     g8QsfJhFpjY
10    4du1KXBl4YU
11    zOOmEDwPJX0
12    Prb_osSVE0M
13    KHxdrECEsD0
14    so0ccfs-psI
15    7gShaSuK_PY
16    ep3SLMuRbvg
17    ePO5M5DE01I
18    CLl1RbxDRAs
19    1ZAPwfrtAFY
Name: video_id, dtype: str

In [427]:
print(
    velocity_df[velocity_df["video_id"] == "#NAME?"].shape[0]
)

0

In [428]:
velocity_df["previous_views"] = (
    velocity_df.groupby("video_id")["views"].shift(1)
)

In [429]:
velocity_df["view_growth"] = (
    velocity_df["views"] - velocity_df["previous_views"]
)

In [430]:
velocity_df["view_growth_pct"] = (
    velocity_df["view_growth"]
    / velocity_df["previous_views"].replace(0, pd.NA)
) * 100

In [431]:
velocity_df[
    [
        "video_id",
        "trending_date",
        "views",
        "previous_views",
        "view_growth",
        "view_growth_pct"
    ]
].head(20)

,video_id,trending_date,views,previous_views,view_growth,view_growth_pct
0,kzwfHumJyYc,17.14.11,1096327,NaN,NaN,NaN
1,zUZ1z7FwLc8,17.14.11,590101,NaN,NaN,NaN
2,10L1hZ9qa58,17.14.11,473988,NaN,NaN,NaN
3,N1vE8iiEg64,17.14.11,1242680,NaN,NaN,NaN
4,kJzGH0PVQHQ,17.14.11,464015,NaN,NaN,NaN
5,il_pSa5l98w,17.14.11,6106669,NaN,NaN,NaN
6,7MxiQ4v0EnE,17.14.11,5718766,NaN,NaN,NaN
7,c64I9HNpiOY,17.14.11,10588371,NaN,NaN,NaN
8,KObFEYCaRx8,17.14.11,118223,NaN,NaN,NaN
9,g8QsfJhFpjY,17.14.11,969030,NaN,NaN,NaN
10,4du1KXBl4YU,17.14.11,632747,NaN,NaN,NaN
11,zOOmEDwPJX0,17.14.11,2348107,NaN,NaN,NaN
12,Prb_osSVE0M,17.14.11,156085,NaN,NaN,NaN
13,KHxdrECEsD0,17.14.11,472413,NaN,NaN,NaN
14,so0ccfs-psI,17.14.11,836006,NaN,NaN,NaN
15,7gShaSuK_PY,17.14.11,89531,NaN,NaN,NaN
16,ep3SLMuRbvg,17.14.11,344545,NaN,NaN,NaN
17,ePO5M5DE01I,17.14.11,35885754,NaN,NaN,NaN
18,CLl1RbxDRAs,17.14.11,209599,NaN,NaN,NaN
19,1ZAPwfrtAFY,17.14.11,2418783,NaN,NaN,NaN

In [432]:
velocity_df["view_velocity"] = (
    velocity_df["view_growth_pct"] / 100
)

In [433]:
velocity_df["engagement_rate"] = (
    (
        velocity_df["likes"] +
        velocity_df["comment_count"]
    )
    / velocity_df["views"].replace(0, pd.NA)
) * 100

In [434]:
velocity_df["trend_velocity_score"] = (
    velocity_df["view_velocity"] *
    velocity_df["engagement_rate"]
)

In [435]:
velocity_df["trend_status"] = pd.cut(
    velocity_df["trend_velocity_score"],
    bins=[
        -float("inf"),
        0,
        1,
        5,
        float("inf")
    ],
    labels=[
        "Declining",
        "Stable",
        "Growing",
        "Exploding"
    ]
)

In [436]:
top_trending = velocity_df.sort_values(
    "trend_velocity_score",
    ascending=False
)

In [437]:
latest_date = velocity_df["trending_date"].max()

print("Latest trending date:", latest_date)

Latest trending date: 18.31.05

In [438]:
latest_trends = velocity_df[
    velocity_df["trending_date"] == latest_date
].copy()

In [439]:
latest_trends = latest_trends.sort_values(
    "trend_velocity_score",
    ascending=False
)

In [440]:
print(
    latest_trends[
        [
            "video_id",
            "views",
            "view_growth_pct",
            "engagement_rate",
            "trend_velocity_score",
            "trend_status"
        ]
    ].head(10)
)

          video_id    views  view_growth_pct  engagement_rate  \
34242  qjx-PP8lw1Y   362829       213.383372         5.750643
34309  aeVtTvVr-2c   449894       149.928615         5.778028
34201  1ku3uA75MbI   729072       110.730895         7.586494
34249  QZs5SiM-C2E   785476        59.930447         9.595074
34241  MZO8IgL2mN4   469165        85.916894         5.431991
34190  b_7I7kANNgI   954093       180.208462         2.400709
34270  mf5QyS5S54o   240807        75.448809         5.116546
34220  TxxbY4WddK4  1409399        48.336554         6.063861
34246  SDCffmveHp0   617807       153.985488         1.827108
34207  QCybY-kdhIU  1483016       146.244685         1.554467

       trend_velocity_score trend_status
34242             12.270916    Exploding
34309              8.662917    Exploding
34201              8.400592    Exploding
34249              5.750370    Exploding
34241              4.666998      Growing
34190              4.326281      Growing
34270              3.860373      Growing
34220              2.931062      Growing
34246              2.813481      Growing
34207              2.273326      Growing

In [441]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [442]:
velocity_df.to_csv(
    "../data/processed/trend_velocity.csv",
    index=False
)

In [443]:
import sqlite3

conn = sqlite3.connect(
    "../data/youtube_trendpulse.db"
)

In [444]:
velocity_df.to_sql(
    "trend_velocity",
    conn,
    if_exists="replace",
    index=False
)

36841

In [445]:
query = """
SELECT *
FROM trend_velocity
LIMIT 5
"""

print(pd.read_sql_query(query, conn))

      video_id trending_date    views  likes  comment_count previous_views  \
0  kzwfHumJyYc      17.14.11  1096327  33966            882           None
1  zUZ1z7FwLc8      17.14.11   590101    735              0           None
2  10L1hZ9qa58      17.14.11   473988   2011            149           None
3  N1vE8iiEg64      17.14.11  1242680  70353           2684           None
4  kJzGH0PVQHQ      17.14.11   464015    492             66           None

  view_growth view_growth_pct view_velocity  engagement_rate  \
0        None            None          None         3.178614
1        None            None          None         0.124555
2        None            None          None         0.455708
3        None            None          None         5.877378
4        None            None          None         0.120255

  trend_velocity_score trend_status
0                 None         None
1                 None         None
2                 None         None
3                 None         None
4                 None         None

In [446]:
conn.close()

In [447]:
trend_df = velocity_df.copy()

In [448]:
trend_df["velocity_percentile"] = (
    trend_df["view_velocity"]
    .rank(pct=True)
)

In [449]:
trend_df["engagement_percentile"] = (
    trend_df["engagement_rate"]
    .rank(pct=True)
)

In [450]:
trend_df["growth_score"] = (
    trend_df["velocity_percentile"] * 100
)

In [451]:
print(
    trend_df[
        [
            "video_id",
            "view_velocity",
            "growth_score"
        ]
    ].head(20)
)

       video_id  view_velocity  growth_score
0   kzwfHumJyYc            NaN           NaN
1   zUZ1z7FwLc8            NaN           NaN
2   10L1hZ9qa58            NaN           NaN
3   N1vE8iiEg64            NaN           NaN
4   kJzGH0PVQHQ            NaN           NaN
5   il_pSa5l98w            NaN           NaN
6   7MxiQ4v0EnE            NaN           NaN
7   c64I9HNpiOY            NaN           NaN
8   KObFEYCaRx8            NaN           NaN
9   g8QsfJhFpjY            NaN           NaN
10  4du1KXBl4YU            NaN           NaN
11  zOOmEDwPJX0            NaN           NaN
12  Prb_osSVE0M            NaN           NaN
13  KHxdrECEsD0            NaN           NaN
14  so0ccfs-psI            NaN           NaN
15  7gShaSuK_PY            NaN           NaN
16  ep3SLMuRbvg            NaN           NaN
17  ePO5M5DE01I            NaN           NaN
18  CLl1RbxDRAs            NaN           NaN
19  1ZAPwfrtAFY            NaN           NaN

In [452]:
trend_df["engagement_score"] = (
    trend_df["engagement_percentile"] * 100
)

In [453]:
trend_df["emerging_trend_score"] = (
    trend_df["growth_score"] * 0.7
    +
    trend_df["engagement_score"] * 0.3
)

In [454]:
trend_df["emerging_status"] = pd.cut(
    trend_df["emerging_trend_score"],
    bins=[
        -float("inf"),
        40,
        60,
        80,
        float("inf")
    ],
    labels=[
        "Normal",
        "Growing",
        "Hot",
        "Emerging"
    ]
)

In [455]:
emerging_trends = trend_df[
    trend_df["emerging_status"] == "Emerging"
].copy()

In [456]:
print(
    emerging_trends[
        [
            "video_id",
            "views",
            "view_growth_pct",
            "engagement_rate",
            "emerging_trend_score",
            "emerging_status"
        ]
    ].head(20)
)

        video_id    views  view_growth_pct  engagement_rate  \
223  ep3SLMuRbvg   645886        87.460564         6.357159
237  K6JyjjNnTlg   267990       134.121923         1.083623
243  PVyuSPi0brM   142890       478.502024         0.927987
244  1ZAPwfrtAFY  4632016        91.501925         3.239799
247  g7BHnHzwOVo   513503        94.623717         2.961229
248  bx-QX2ZPH60   397157        66.427251         2.966837
299  t7I8EBOTx8Y   128872       241.057535         1.869297
308  NDuOXWe4KW8   147609       137.500603         1.023650
348  A_XgvSkbCvM    36332       113.642244         1.337664
393  qEf_2YN1XaA    42124        62.993345         5.160953
406  NXcGCGGtJI0   573564        75.391108         3.721468
429  vkr74kiEPM4   234050        80.635950         3.778680
437  wvHYHVq9xio   237316        78.092965        11.019063
444  SYtxYDSUF90   733339       107.282631         5.573548
453  ShoT7k3w6_M    72971       316.834228         3.854956
547  jLsNEN-rnG0    31257        74.620112        10.388073
578  UQ5M6AsmBUI    42652        42.567771        11.188221
595  Y83L3JOlWHo   707236       128.346157         4.669587
639  viUWXtRLNgo   186213        68.552110        10.168463
661  MaR_mrHmo7Q   106452       213.094118         0.957239

     emerging_trend_score emerging_status
223             89.519027        Emerging
237             81.659561        Emerging
243             83.580039        Emerging
244             85.926018        Emerging
247             85.720385        Emerging
248             80.812563        Emerging
299             87.982258        Emerging
308             81.347172        Emerging
348             81.970335        Emerging
393             83.401634        Emerging
406             84.331242        Emerging
429             85.408917        Emerging
437             90.509993        Emerging
444             90.842100        Emerging
453             93.357095        Emerging
547             89.625580        Emerging
578             80.011318        Emerging
595             91.264096        Emerging
639             88.183066        Emerging
661             82.696829        Emerging

In [457]:
hot_trends = trend_df[
    trend_df["emerging_status"] == "Hot"
].copy()

In [458]:
hot_trends = hot_trends.sort_values(
    "emerging_trend_score",
    ascending=False
)

In [459]:
print(
    hot_trends[
        [
            "video_id",
            "views",
            "view_growth_pct",
            "engagement_rate",
            "emerging_trend_score"
        ]
    ].head(20)
)

          video_id    views  view_growth_pct  engagement_rate  \
22533  8UJiXIJiWtQ   370064        45.553519         7.962407
29487  IiD-hBGmTIs  1924401       192.469270         0.733059
30307  koQ_MZcIF_U   357160        88.202810         1.443331
7158   HDyC5WFXbPc   364311        53.976949         4.546116
26198  DInfmi-YIiw   589152        67.765451         2.482212
34807  fnHorZxcwyM   309937        57.486713         3.797546
12469  96AQc5_YUMs    34518        60.548837         3.291037
17659  9NWqtAcm5mg    87648        78.734859         1.767296
32832  nD5f7xoxsNI   407588       138.415508         0.864599
4862   71wAEnP9NpM   669847        66.838192         2.562078
10522  Ye4z35i1b2Q  3257549        97.549094         1.224540
21761  yE8lyo6OmpU   166813        56.972400         3.857613
417    g6ydk-TTdYM   445904        60.809558         3.237917
11753  VK48OAx1TO8   618586        54.173957         4.459202
3476   sCS0ZP2FOvs    98163        52.597625         4.903069
36422  rZYI9pR16kA    81964        54.964834         4.309209
30266  fQvYMRtjQJU   612871       147.719731         0.826928
29162  RWFdAgFRDfI   574803        69.283758         2.343760
6484   1Uye3kSh6Hw   189902        71.810368         2.133206
17272  emZFn3qK2BM  2416985       103.464645         1.134844

       emerging_trend_score
22533             79.995078
29487             79.993339
30307             79.979349
7158              79.979144
26198             79.975601
34807             79.969169
12469             79.967295
17659             79.960475
32832             79.946087
4862              79.941424
10522             79.940513
21761             79.933033
417               79.928437
11753             79.923034
3476              79.920275
36422             79.915539
30266             79.910748
29162             79.906923
6484              79.905849
17272             79.903483

In [460]:
trend_df["trend_alert"] = "NO ALERT"

In [461]:
trend_df.loc[
    trend_df["emerging_status"] == "Hot",
    "trend_alert"
] = "WATCH"

In [462]:
trend_df.loc[
    trend_df["emerging_status"] == "Emerging",
    "trend_alert"
] = "🚨 TREND ALERT"

In [463]:
emerging_report = trend_df[
    [
        "video_id",
        "trending_date",
        "views",
        "view_growth",
        "view_growth_pct",
        "view_velocity",
        "engagement_rate",
        "emerging_trend_score",
        "emerging_status",
        "trend_alert"
    ]
].copy()

In [464]:
emerging_report = emerging_report.sort_values(
    "emerging_trend_score",
    ascending=False
)

In [465]:
print(emerging_report.head(20))

          video_id trending_date    views  view_growth  view_growth_pct  \
34906  ZqG90jzu2QE      18.04.06   529146     381260.0       257.806689
34921  2s4GMLkTNv0      18.04.06  3733710    2584077.0       224.774080
27565  tHmAPWOo2jY      18.24.04  3030716    2262784.0       294.659423
19315  3VCMKI3vbX8      18.02.03   213449     149308.0       232.780905
12317  RiyEX5gtyVY      18.21.01   228067     144594.0       173.222479
20435  s0_G-Kk6-Yg      18.09.03   563003     407710.0       262.542420
35182  AaK8pFtg1BI      18.05.06    73736      50900.0       222.893677
24949  u_nrjjXlO1M      18.04.04   355997     300130.0       537.222332
18970  xTpm58ztqEY      18.28.02   189533     151583.0       399.428195
16795  BHHIlEv_YdY      18.15.02   527810     321683.0       156.060584
5624   h1bV5A0Mqq4      17.14.12  1310211     954666.0       268.507784
27483  Xr2UE5SQCIU      18.24.04  1682462    1014129.0       151.740076
10284  hHmYqnUftpA      18.08.01   376401     234184.0       164.666671
28788  niKoi5npA8w      18.01.05  1223455     750777.0       158.834767
29359  DkeiKbqa02g      18.04.05  4177468    3150600.0       306.816455
3958   gcx2UexjG3Y      17.05.12   184755     119877.0       184.772958
10875  SgdVQY4kbho      18.13.01   226950     147598.0       186.004133
24796  IpPfKlT4hO0      18.03.04    56790      42565.0       299.226714
3128   j_Vlg4K05s8      17.30.11  1375860    1092118.0       384.898253
27541  lec5QqY_KXg      18.24.04    51871      34773.0       203.374664

       view_velocity  engagement_rate  emerging_trend_score emerging_status  \
34906       2.578067        10.229691             98.161489        Emerging
34921       2.247741        10.507163             97.945387        Emerging
27565       2.946594         8.023418             97.436313        Emerging
19315       2.327809         8.836303             97.359776        Emerging
12317       1.732225        11.702701             97.279194        Emerging
20435       2.625424         7.834772             97.104960        Emerging
35182       2.228937         8.172399             96.950157        Emerging
24949       5.372223         6.632359             96.884732        Emerging
18970       3.994282         6.574581             96.717634        Emerging
16795       1.560606        11.235672             96.709527        Emerging
5624        2.685078         7.068251             96.627605        Emerging
27483       1.517401        11.259155             96.603957        Emerging
10284       1.646667         9.232972             96.289007        Emerging
28788       1.588348         9.638769             96.269829        Emerging
29359       3.068165         6.299917             96.237782        Emerging
3958        1.847730         8.045790             96.195864        Emerging
10875       1.860041         7.902181             96.141401        Emerging
24796       2.992267         6.168339             96.081699        Emerging
3128        3.848983         5.816071             95.972398        Emerging
27541       2.033747         7.133080             95.954609        Emerging

         trend_alert
34906  🚨 TREND ALERT
34921  🚨 TREND ALERT
27565  🚨 TREND ALERT
19315  🚨 TREND ALERT
12317  🚨 TREND ALERT
20435  🚨 TREND ALERT
35182  🚨 TREND ALERT
24949  🚨 TREND ALERT
18970  🚨 TREND ALERT
16795  🚨 TREND ALERT
5624   🚨 TREND ALERT
27483  🚨 TREND ALERT
10284  🚨 TREND ALERT
28788  🚨 TREND ALERT
29359  🚨 TREND ALERT
3958   🚨 TREND ALERT
10875  🚨 TREND ALERT
24796  🚨 TREND ALERT
3128   🚨 TREND ALERT
27541  🚨 TREND ALERT

In [466]:
emerging_report.to_csv(
    "../data/processed/emerging_trends.csv",
    index=False
)

In [467]:
import sqlite3

conn = sqlite3.connect(
    "../data/youtube_trendpulse.db"
)

In [468]:
emerging_report.to_sql(
    "emerging_trends",
    conn,
    if_exists="replace",
    index=False
)

36841

In [469]:
query = """
SELECT *
FROM emerging_trends
ORDER BY emerging_trend_score DESC
LIMIT 10
"""

print(
    pd.read_sql_query(query, conn)
)

      video_id trending_date    views  view_growth  view_growth_pct  \
0  ZqG90jzu2QE      18.04.06   529146     381260.0       257.806689
1  2s4GMLkTNv0      18.04.06  3733710    2584077.0       224.774080
2  tHmAPWOo2jY      18.24.04  3030716    2262784.0       294.659423
3  3VCMKI3vbX8      18.02.03   213449     149308.0       232.780905
4  RiyEX5gtyVY      18.21.01   228067     144594.0       173.222479
5  s0_G-Kk6-Yg      18.09.03   563003     407710.0       262.542420
6  AaK8pFtg1BI      18.05.06    73736      50900.0       222.893677
7  u_nrjjXlO1M      18.04.04   355997     300130.0       537.222332
8  xTpm58ztqEY      18.28.02   189533     151583.0       399.428195
9  BHHIlEv_YdY      18.15.02   527810     321683.0       156.060584

   view_velocity  engagement_rate  emerging_trend_score emerging_status  \
0       2.578067        10.229691             98.161489        Emerging
1       2.247741        10.507163             97.945387        Emerging
2       2.946594         8.023418             97.436313        Emerging
3       2.327809         8.836303             97.359776        Emerging
4       1.732225        11.702701             97.279194        Emerging
5       2.625424         7.834772             97.104960        Emerging
6       2.228937         8.172399             96.950157        Emerging
7       5.372223         6.632359             96.884732        Emerging
8       3.994282         6.574581             96.717634        Emerging
9       1.560606        11.235672             96.709527        Emerging

     trend_alert
0  🚨 TREND ALERT
1  🚨 TREND ALERT
2  🚨 TREND ALERT
3  🚨 TREND ALERT
4  🚨 TREND ALERT
5  🚨 TREND ALERT
6  🚨 TREND ALERT
7  🚨 TREND ALERT
8  🚨 TREND ALERT
9  🚨 TREND ALERT

In [470]:
conn.close()

In [471]:
print(
    trend_df["emerging_status"].value_counts()
)

emerging_status
Normal      7101
Growing     6180
Hot         5407
Emerging    1847
Name: count, dtype: int64

In [472]:
top_emerging = trend_df[
    trend_df["emerging_status"] == "Emerging"
].sort_values(
    "emerging_trend_score",
    ascending=False
)

In [473]:
trend_df = trend_df.merge(
    clean_df[
        [
            "video_id",
            "title",
            "channel_title",
            "category_id",
            "time_to_trend_days"
        ]
    ].drop_duplicates("video_id"),
    on="video_id",
    how="left"
)

In [474]:
top_emerging = trend_df[
    trend_df["emerging_status"] == "Emerging"
].sort_values(
    "emerging_trend_score",
    ascending=False
)

In [475]:
print(
    top_emerging[
        [
            "video_id",
            "title",
            "channel_title",
            "category_id",
            "views",
            "view_growth_pct",
            "engagement_rate",
            "emerging_trend_score"
        ]
    ].head(20)
)

          video_id                                              title  \
34906  ZqG90jzu2QE               STERLITE- மெய்ப்பொருள் காண்பது அறிவு
34921  2s4GMLkTNv0                           Dancing Without Moving!?
27565  tHmAPWOo2jY                                      U SLAV U LOSE
19315  3VCMKI3vbX8  Cottonking Presents Struggler Saala Season 2 |...
12317  RiyEX5gtyVY  सोचो की ऐसा हो चूका है और वो मिल जायेगा | The ...
20435  s0_G-Kk6-Yg  Unhappy Women's Day ft. Lakshmipriyaa | #Fully...
35182  AaK8pFtg1BI  Kitabaan Vala Rakhna || Tribute to Sikh martyr...
24949  u_nrjjXlO1M                   Boys VS. Girls : Morning Routine
18970  xTpm58ztqEY  சிரியா பிரச்னை | சிரியாவில்  நடப்பது என்ன?|Syr...
16795  BHHIlEv_YdY  Dino James - Tujhe Meri Yadein Feat. Akriti Ka...
5624   h1bV5A0Mqq4                 Gaali Vaaluga - A Tribute To #PSPK
27483  Xr2UE5SQCIU                   THE FOUL PLAY | ROUND2HELL | R2H
10284  hHmYqnUftpA                       A Rickshaw Puller was Crying
28788  niKoi5npA8w  Epic - Call Clash Prank on Cute Girls Bhojpuri...
29359  DkeiKbqa02g  Calvin Harris, Dua Lipa - One Kiss (Official V...
3958   gcx2UexjG3Y                    A Man Insults A Street Salesman
10875  SgdVQY4kbho              Girls Will Be Girls | SahibNoor Singh
24796  IpPfKlT4hO0  2 April 2018 - The Hindu Editorial News Paper ...
3128   j_Vlg4K05s8  Dil De Kareeb | Garry Sandhu ( Full Video ) | ...
27541  lec5QqY_KXg  23 April 2018 - The Hindu Editorial News Paper...

                                channel_title  category_id    views  \
34906            Lets Make Engineering Simple           27   529146
34921                                nigahiga           24  3733710
27565                               PewDiePie           24  3030716
19315                                  chavat           24   213449
12317                               FactTechz           28   228067
20435                                   Fully            1   563003
35182               White Notes Entertainment           10    73736
24949                             Rickshawali           24   355997
18970                                  Kichdy           24   189533
16795                              Dino James           10   527810
5624                             Aditya Music           10  1310211
27483                              Round2hell           23  1682462
10284                        ActorVarunPruthi           24   376401
28788  The HunGama Films - Ab Mauj Legi Dilli           24  1223455
29359                        CalvinHarrisVEVO           10  4177468
3958                         ActorVarunPruthi           24   184755
10875                         SahibNoor Singh           24   226950
24796                      Study IQ education           27    56790
3128                      Fresh Media Records           10  1375860
27541                      Study IQ education           27    51871

       view_growth_pct  engagement_rate  emerging_trend_score
34906       257.806689        10.229691             98.161489
34921       224.774080        10.507163             97.945387
27565       294.659423         8.023418             97.436313
19315       232.780905         8.836303             97.359776
12317       173.222479        11.702701             97.279194
20435       262.542420         7.834772             97.104960
35182       222.893677         8.172399             96.950157
24949       537.222332         6.632359             96.884732
18970       399.428195         6.574581             96.717634
16795       156.060584        11.235672             96.709527
5624        268.507784         7.068251             96.627605
27483       151.740076        11.259155             96.603957
10284       164.666671         9.232972             96.289007
28788       158.834767         9.638769             96.269829
29359       306.816455         6.299917             96.237782
3958        184.772958         8.045790             96.195864
10875       186.004133         7.902181             96.141401
24796       299.226714         6.168339             96.081699
3128        384.898253         5.816071             95.972398
27541       203.374664         7.133080             95.954609

In [476]:
category_analysis = trend_df.groupby(
    "category_id"
).agg(
    videos=("video_id", "count"),
    avg_growth=("view_growth_pct", "mean"),
    avg_engagement=("engagement_rate", "mean"),
    avg_trend_score=("emerging_trend_score", "mean")
).reset_index()

In [477]:
category_analysis = category_analysis.sort_values(
    "avg_trend_score",
    ascending=False
)

In [478]:
print(category_analysis.head(10))

    category_id  videos  avg_growth  avg_engagement  avg_trend_score
12           27    1220   48.939219        5.995998        64.831709
13           28     552   32.433606       10.573901        60.607154
14           29     105   32.078992        3.458744        59.058914
8            23    3397   29.531371        5.912630        56.926102
11           26     840   53.105101        1.715018        56.773086
1             2      70   40.099241        2.580863        54.728690
3            15       2   10.963572        8.523166        54.000346
2            10    3796   35.438036        2.781079        53.071100
0             1    1638   36.846073        2.175139        50.920811
15           30      16   48.064179        1.922697        49.714332

In [479]:
print("time_to_trend_days" in clean_df.columns)

True

In [480]:
trend_df = trend_df.merge(
    clean_df[
        ["video_id", "time_to_trend_days"]
    ].drop_duplicates("video_id"),
    on="video_id",
    how="left"
)

In [481]:
trend_df["time_to_trend_days"] = trend_df["time_to_trend_days_x"]

trend_df = trend_df.drop(
    columns=["time_to_trend_days_x", "time_to_trend_days_y"]
)

In [482]:
print(trend_df["time_to_trend_days"].head(10))

0    2
1    1
2    2
3    2
4    1
5    4
6    3
7    3
8    1
9    2
Name: time_to_trend_days, dtype: int64

In [483]:
print(
    trend_df.groupby(
        pd.cut(
            trend_df["time_to_trend_days"],
            bins=[-1, 1, 3, 7, float("inf")],
            labels=[
                "0-1 days",
                "2-3 days",
                "4-7 days",
                "8+ days"
            ]
        )
    )["emerging_trend_score"].mean()
)

time_to_trend_days
0-1 days    51.314063
2-3 days    44.926161
4-7 days    43.998627
8+ days     51.184314
Name: emerging_trend_score, dtype: float64

In [484]:
print(
    trend_df[
        [
            "view_growth_pct",
            "engagement_rate",
            "emerging_trend_score"
        ]
    ].corr()
)

                      view_growth_pct  engagement_rate  emerging_trend_score
view_growth_pct              1.000000        -0.074573              0.621429
engagement_rate             -0.074573         1.000000              0.237570
emerging_trend_score         0.621429         0.237570              1.000000

In [485]:
channel_analysis = trend_df.groupby(
    "channel_title"
).agg(
    videos=("video_id", "count"),
    avg_growth=("view_growth_pct", "mean"),
    avg_engagement=("engagement_rate", "mean"),
    avg_trend_score=("emerging_trend_score", "mean")
).reset_index()

In [486]:
channel_analysis = channel_analysis.sort_values(
    "avg_trend_score",
    ascending=False
)

In [487]:
print(channel_analysis.head(20))

                              channel_title  videos  avg_growth  \
194                            Captain Nick       6  106.280193
568                             Linkin Park       2   96.798725
513   Kantriguyz - Hyderabadi Comedy Videos       3   93.152359
1016                           Sports Blast       2  212.733258
702                             Nari Kootam       2  100.489060
709                      Nee Yaaruda Komali       5   81.692844
512                             Kantri Guyz       3  113.583339
1234                         UnErase Poetry       5  116.686644
711              Nee Yaaruda Komali ( NYK )       5   76.547782
277                   Disney Movie Trailers       5  205.967656
653                           Motion Frames       3   81.948605
863                           Rahim Pardesi       2   93.752982
969                        Shahrukh K Adnan       7   65.472058
1021                   Sri Sri Ravi Shankar      11   72.135771
514                           KatyPerryVEVO       3  123.325589
992                             Sindhionism      11   77.774001
192                Calvary Temple Hyderabad      35   75.188704
1336                        Young Holy Team       6  101.204025
1216                      Trending Programs       2  130.666437
1258                     Veena's Curryworld      10   95.508700

      avg_engagement  avg_trend_score
194        15.536725        94.204214
568        12.680172        92.792996
513         9.609693        91.760744
1016        4.305101        91.335391
702         7.701401        90.908671
709        10.674521        90.879551
512         7.799781        89.698788
1234        8.252673        89.660123
711         9.501240        89.015964
277         2.556019        88.769217
653         7.030086        88.240714
863         4.924107        87.562446
969        12.112824        87.520641
1021        6.529872        87.436419
514         6.915871        87.338991
992        12.514067        87.103934
192         8.704388        87.006792
1336        3.613952        86.781369
1216        2.107451        85.513498
1258        4.085030        85.419974

In [488]:
why_analysis = trend_df[
    [
        "video_id",
        "title",
        "channel_title",
        "category_id",
        "views",
        "view_growth_pct",
        "view_velocity",
        "engagement_rate",
        "time_to_trend_days",
        "emerging_trend_score",
        "emerging_status",
        "trend_alert"
    ]
].copy()

In [489]:
why_analysis.to_csv(
    "../data/processed/why_analysis.csv",
    index=False
)

In [490]:
import os

os.makedirs("../reports", exist_ok=True)

In [491]:
report_df = trend_df[
    [
        "video_id",
        "title",
        "channel_title",
        "category_id",
        "views",
        "view_growth",
        "view_growth_pct",
        "view_velocity",
        "engagement_rate",
        "emerging_trend_score",
        "emerging_status",
        "trend_alert"
    ]
].copy()

In [492]:
alert_report = report_df[
    report_df["trend_alert"] != "NO ALERT"
].copy()

In [493]:
alert_report = alert_report.sort_values(
    "emerging_trend_score",
    ascending=False
)

In [494]:
print(alert_report.head(20))

          video_id                                              title  \
34906  ZqG90jzu2QE               STERLITE- மெய்ப்பொருள் காண்பது அறிவு
34921  2s4GMLkTNv0                           Dancing Without Moving!?
27565  tHmAPWOo2jY                                      U SLAV U LOSE
19315  3VCMKI3vbX8  Cottonking Presents Struggler Saala Season 2 |...
12317  RiyEX5gtyVY  सोचो की ऐसा हो चूका है और वो मिल जायेगा | The ...
20435  s0_G-Kk6-Yg  Unhappy Women's Day ft. Lakshmipriyaa | #Fully...
35182  AaK8pFtg1BI  Kitabaan Vala Rakhna || Tribute to Sikh martyr...
24949  u_nrjjXlO1M                   Boys VS. Girls : Morning Routine
18970  xTpm58ztqEY  சிரியா பிரச்னை | சிரியாவில்  நடப்பது என்ன?|Syr...
16795  BHHIlEv_YdY  Dino James - Tujhe Meri Yadein Feat. Akriti Ka...
5624   h1bV5A0Mqq4                 Gaali Vaaluga - A Tribute To #PSPK
27483  Xr2UE5SQCIU                   THE FOUL PLAY | ROUND2HELL | R2H
10284  hHmYqnUftpA                       A Rickshaw Puller was Crying
28788  niKoi5npA8w  Epic - Call Clash Prank on Cute Girls Bhojpuri...
29359  DkeiKbqa02g  Calvin Harris, Dua Lipa - One Kiss (Official V...
3958   gcx2UexjG3Y                    A Man Insults A Street Salesman
10875  SgdVQY4kbho              Girls Will Be Girls | SahibNoor Singh
24796  IpPfKlT4hO0  2 April 2018 - The Hindu Editorial News Paper ...
3128   j_Vlg4K05s8  Dil De Kareeb | Garry Sandhu ( Full Video ) | ...
27541  lec5QqY_KXg  23 April 2018 - The Hindu Editorial News Paper...

                                channel_title  category_id    views  \
34906            Lets Make Engineering Simple           27   529146
34921                                nigahiga           24  3733710
27565                               PewDiePie           24  3030716
19315                                  chavat           24   213449
12317                               FactTechz           28   228067
20435                                   Fully            1   563003
35182               White Notes Entertainment           10    73736
24949                             Rickshawali           24   355997
18970                                  Kichdy           24   189533
16795                              Dino James           10   527810
5624                             Aditya Music           10  1310211
27483                              Round2hell           23  1682462
10284                        ActorVarunPruthi           24   376401
28788  The HunGama Films - Ab Mauj Legi Dilli           24  1223455
29359                        CalvinHarrisVEVO           10  4177468
3958                         ActorVarunPruthi           24   184755
10875                         SahibNoor Singh           24   226950
24796                      Study IQ education           27    56790
3128                      Fresh Media Records           10  1375860
27541                      Study IQ education           27    51871

       view_growth  view_growth_pct  view_velocity  engagement_rate  \
34906     381260.0       257.806689       2.578067        10.229691
34921    2584077.0       224.774080       2.247741        10.507163
27565    2262784.0       294.659423       2.946594         8.023418
19315     149308.0       232.780905       2.327809         8.836303
12317     144594.0       173.222479       1.732225        11.702701
20435     407710.0       262.542420       2.625424         7.834772
35182      50900.0       222.893677       2.228937         8.172399
24949     300130.0       537.222332       5.372223         6.632359
18970     151583.0       399.428195       3.994282         6.574581
16795     321683.0       156.060584       1.560606        11.235672
5624      954666.0       268.507784       2.685078         7.068251
27483    1014129.0       151.740076       1.517401        11.259155
10284     234184.0       164.666671       1.646667         9.232972
28788     750777.0       158.834767       1.588348         9.638769
29359    3150600.0       306.816455       3.068165         6.299917
3958      119877.0       184.772958       1.847730         8.045790
10875     147598.0       186.004133       1.860041         7.902181
24796      42565.0       299.226714       2.992267         6.168339
3128     1092118.0       384.898253       3.848983         5.816071
27541      34773.0       203.374664       2.033747         7.133080

       emerging_trend_score emerging_status    trend_alert
34906             98.161489        Emerging  🚨 TREND ALERT
34921             97.945387        Emerging  🚨 TREND ALERT
27565             97.436313        Emerging  🚨 TREND ALERT
19315             97.359776        Emerging  🚨 TREND ALERT
12317             97.279194        Emerging  🚨 TREND ALERT
20435             97.104960        Emerging  🚨 TREND ALERT
35182             96.950157        Emerging  🚨 TREND ALERT
24949             96.884732        Emerging  🚨 TREND ALERT
18970             96.717634        Emerging  🚨 TREND ALERT
16795             96.709527        Emerging  🚨 TREND ALERT
5624              96.627605        Emerging  🚨 TREND ALERT
27483             96.603957        Emerging  🚨 TREND ALERT
10284             96.289007        Emerging  🚨 TREND ALERT
28788             96.269829        Emerging  🚨 TREND ALERT
29359             96.237782        Emerging  🚨 TREND ALERT
3958              96.195864        Emerging  🚨 TREND ALERT
10875             96.141401        Emerging  🚨 TREND ALERT
24796             96.081699        Emerging  🚨 TREND ALERT
3128              95.972398        Emerging  🚨 TREND ALERT
27541             95.954609        Emerging  🚨 TREND ALERT

In [495]:
report_path = "../reports/YouTube_TrendPulse_Report.xlsx"

with pd.ExcelWriter(report_path, engine="openpyxl") as writer:
    report_df.to_excel(
        writer,
        sheet_name="All Trends",
        index=False
    )

    alert_report.to_excel(
        writer,
        sheet_name="Trend Alerts",
        index=False
    )

print("Report created:", report_path)

Report created: ../reports/YouTube_TrendPulse_Report.xlsx

In [496]:
summary = {
    "Total Videos": len(trend_df),
    "Emerging Videos": (
        trend_df["emerging_status"] == "Emerging"
    ).sum(),
    "Hot Videos": (
        trend_df["emerging_status"] == "Hot"
    ).sum(),
    "Average Growth %": trend_df["view_growth_pct"].mean(),
    "Average Engagement %": trend_df["engagement_rate"].mean(),
    "Average Trend Score": trend_df["emerging_trend_score"].mean()
}

In [497]:
summary_df = pd.DataFrame(
    list(summary.items()),
    columns=["Metric", "Value"]
)

In [498]:
print(summary_df)

                 Metric         Value
0          Total Videos  36841.000000
1       Emerging Videos   1847.000000
2            Hot Videos   5407.000000
3      Average Growth %     36.638879
4  Average Engagement %      2.466145
5   Average Trend Score     50.451071

In [499]:
with pd.ExcelWriter(report_path, engine="openpyxl") as writer:

    summary_df.to_excel(
        writer,
        sheet_name="Summary",
        index=False
    )

    report_df.to_excel(
        writer,
        sheet_name="All Trends",
        index=False
    )

    alert_report.to_excel(
        writer,
        sheet_name="Trend Alerts",
        index=False
    )

print("Automated report updated successfully.")

Automated report updated successfully.

In [500]:
if len(alert_report) > 0:

    print("🚨 TREND PULSE ALERT")
    print("--------------------")

    for _, row in alert_report.head(10).iterrows():

        print(
            f"{row['trend_alert']} | "
            f"{row['title']} | "
            f"Score: {row['emerging_trend_score']:.2f}"
        )

else:

    print("No significant trend alerts today.")

🚨 TREND PULSE ALERT
--------------------
🚨 TREND ALERT | STERLITE- மெய்ப்பொருள் காண்பது அறிவு | Score: 98.16
🚨 TREND ALERT | Dancing Without Moving!? | Score: 97.95
🚨 TREND ALERT | U SLAV U LOSE | Score: 97.44
🚨 TREND ALERT | Cottonking Presents Struggler Saala Season 2 | Episode 01 | Score: 97.36
🚨 TREND ALERT | सोचो की ऐसा हो चूका है और वो मिल जायेगा | The Act as If Technique (Law of Attraction) | Score: 97.28
🚨 TREND ALERT | Unhappy Women's Day ft. Lakshmipriyaa | #FullyFearless | Fully | Score: 97.10
🚨 TREND ALERT | Kitabaan Vala Rakhna || Tribute to Sikh martyrs of '84 || Harmanjeet || Manpreet | Score: 96.95
🚨 TREND ALERT | Boys VS. Girls : Morning Routine | Score: 96.88
🚨 TREND ALERT | சிரியா பிரச்னை | சிரியாவில்  நடப்பது என்ன?|Syria Problem Explained|Kichdy | Score: 96.72
🚨 TREND ALERT | Dino James - Tujhe Meri Yadein Feat. Akriti Kakar [Official Video] | Score: 96.71

In [501]:
print("Total videos:", len(trend_df))

print(
    "Emerging:",
    (trend_df["emerging_status"] == "Emerging").sum()
)

print(
    "Hot:",
    (trend_df["emerging_status"] == "Hot").sum()
)

print(
    "Alerts:",
    len(alert_report)
)

Total videos: 36841
Emerging: 1847
Hot: 5407
Alerts: 7254

In [502]:
report_path = "../reports/YouTube_TrendPulse_Report.xlsx"

alert_report.to_excel(
    report_path,
    sheet_name="Trend Alerts",
    index=False
)

print("Report created successfully!")

Report created successfully!

In [510]:
print(clean_df.shape)

print(
    clean_df[
        ["video_id", "trending_date", "views", "likes", "comment_count"]
    ].head(20)
)

(33089, 18)
       video_id trending_date     views   likes  comment_count
0   kzwfHumJyYc    2017-11-14   1096327   33966            882
1   zUZ1z7FwLc8    2017-11-14    590101     735              0
2   10L1hZ9qa58    2017-11-14    473988    2011            149
3   N1vE8iiEg64    2017-11-14   1242680   70353           2684
4   kJzGH0PVQHQ    2017-11-14    464015     492             66
5   il_pSa5l98w    2017-11-14   6106669   98612           4763
6   7MxiQ4v0EnE    2017-11-14   5718766  127477           8063
7   c64I9HNpiOY    2017-11-14  10588371  132738          10847
8   KObFEYCaRx8    2017-11-14    118223     520             23
9   g8QsfJhFpjY    2017-11-14    969030   59798           2404
10  4du1KXBl4YU    2017-11-14    632747    4330           2869
11  zOOmEDwPJX0    2017-11-14   2348107   32834           1743
12  Prb_osSVE0M    2017-11-14    156085     716              0
13  KHxdrECEsD0    2017-11-14    472413    2611            174
14  so0ccfs-psI    2017-11-14    836006   24460            594
15  7gShaSuK_PY    2017-11-14     89531     238             18
16  ep3SLMuRbvg    2017-11-14    344545   25717           2870
17  ePO5M5DE01I    2017-11-14  35885754  829362         101117
18  CLl1RbxDRAs    2017-11-14    209599   14070           1105
19  1ZAPwfrtAFY    2017-11-14   2418783   97187          12703

In [511]:
# Start fresh from the correct clean data
velocity_df = clean_df[
    ["video_id", "trending_date", "views", "likes", "comment_count"]
].copy()

# Sort each video chronologically
velocity_df = velocity_df.sort_values(
    ["video_id", "trending_date"]
).reset_index(drop=True)

# Previous day's views for the same video
velocity_df["previous_views"] = (
    velocity_df.groupby("video_id")["views"].shift(1)
)

# View growth
velocity_df["view_growth"] = (
    velocity_df["views"] - velocity_df["previous_views"]
)

# Percentage growth
velocity_df["view_growth_pct"] = (
    velocity_df["view_growth"]
    / velocity_df["previous_views"]
) * 100

# View velocity
velocity_df["view_velocity"] = (
    velocity_df["view_growth_pct"] / 100
)

# Engagement rate
velocity_df["engagement_rate"] = (
    (velocity_df["likes"] + velocity_df["comment_count"])
    / velocity_df["views"]
) * 100

print(velocity_df.shape)
print(velocity_df.head(10))

(33089, 10)
  video_id trending_date   views  likes  comment_count  previous_views  \
0   #NAME?    2017-11-14   31052     36              2             NaN
1   #NAME?    2017-11-14   30659    180              3         31052.0
2   #NAME?    2017-11-14  743321   2570            294         30659.0
3   #NAME?    2017-11-15   28816    376             29        743321.0
4   #NAME?    2017-11-15   14529   1018             83         28816.0
5   #NAME?    2017-11-16   36956    442             29         14529.0
6   #NAME?    2017-11-16   20289   1221             95         36956.0
7   #NAME?    2017-11-16   12462     74              4         20289.0
8   #NAME?    2017-11-17   40104    170             12         12462.0
9   #NAME?    2017-11-18  228047   1395           1928         40104.0

   view_growth  view_growth_pct  view_velocity  engagement_rate
0          NaN              NaN            NaN         0.122375
1       -393.0        -1.265619      -0.012656         0.596888
2     712662.0      2324.478946      23.244789         0.385298
3    -714505.0       -96.123344      -0.961233         1.405469
4     -14287.0       -49.580094      -0.495801         7.577948
5      22427.0       154.360245       1.543602         1.274489
6     -16667.0       -45.099578      -0.450996         6.486273
7      -7827.0       -38.577554      -0.385776         0.625903
8      27642.0       221.810303       2.218103         0.453820
9     187943.0       468.639038       4.686390         1.457156

In [512]:
print(clean_df["video_id"].head(20))
print("\nUnique IDs:", clean_df["video_id"].nunique())
print("\n#NAME? count:", (clean_df["video_id"] == "#NAME?").sum())

0     kzwfHumJyYc
1     zUZ1z7FwLc8
2     10L1hZ9qa58
3     N1vE8iiEg64
4     kJzGH0PVQHQ
5     il_pSa5l98w
6     7MxiQ4v0EnE
7     c64I9HNpiOY
8     KObFEYCaRx8
9     g8QsfJhFpjY
10    4du1KXBl4YU
11    zOOmEDwPJX0
12    Prb_osSVE0M
13    KHxdrECEsD0
14    so0ccfs-psI
15    7gShaSuK_PY
16    ep3SLMuRbvg
17    ePO5M5DE01I
18    CLl1RbxDRAs
19    1ZAPwfrtAFY
Name: video_id, dtype: str

Unique IDs: 16307

#NAME? count: 442

In [513]:
print(velocity_df.shape)
print(velocity_df.dtypes)
print(velocity_df[[
    "video_id",
    "trending_date",
    "views",
    "previous_views",
    "view_growth",
    "view_growth_pct",
    "view_velocity",
    "engagement_rate"
]].head(10))

(33089, 10)
video_id                      str
trending_date      datetime64[us]
views                       int64
likes                       int64
comment_count               int64
previous_views            float64
view_growth               float64
view_growth_pct           float64
view_velocity             float64
engagement_rate           float64
dtype: object
  video_id trending_date   views  previous_views  view_growth  \
0   #NAME?    2017-11-14   31052             NaN          NaN
1   #NAME?    2017-11-14   30659         31052.0       -393.0
2   #NAME?    2017-11-14  743321         30659.0     712662.0
3   #NAME?    2017-11-15   28816        743321.0    -714505.0
4   #NAME?    2017-11-15   14529         28816.0     -14287.0
5   #NAME?    2017-11-16   36956         14529.0      22427.0
6   #NAME?    2017-11-16   20289         36956.0     -16667.0
7   #NAME?    2017-11-16   12462         20289.0      -7827.0
8   #NAME?    2017-11-17   40104         12462.0      27642.0
9   #NAME?    2017-11-18  228047         40104.0     187943.0

   view_growth_pct  view_velocity  engagement_rate
0              NaN            NaN         0.122375
1        -1.265619      -0.012656         0.596888
2      2324.478946      23.244789         0.385298
3       -96.123344      -0.961233         1.405469
4       -49.580094      -0.495801         7.577948
5       154.360245       1.543602         1.274489
6       -45.099578      -0.450996         6.486273
7       -38.577554      -0.385776         0.625903
8       221.810303       2.218103         0.453820
9       468.639038       4.686390         1.457156

In [514]:
print(clean_df["video_id"].head(20))
print(clean_df["video_id"].nunique())
print((clean_df["video_id"] == "#NAME?").sum())

0     kzwfHumJyYc
1     zUZ1z7FwLc8
2     10L1hZ9qa58
3     N1vE8iiEg64
4     kJzGH0PVQHQ
5     il_pSa5l98w
6     7MxiQ4v0EnE
7     c64I9HNpiOY
8     KObFEYCaRx8
9     g8QsfJhFpjY
10    4du1KXBl4YU
11    zOOmEDwPJX0
12    Prb_osSVE0M
13    KHxdrECEsD0
14    so0ccfs-psI
15    7gShaSuK_PY
16    ep3SLMuRbvg
17    ePO5M5DE01I
18    CLl1RbxDRAs
19    1ZAPwfrtAFY
Name: video_id, dtype: str
16307
442

In [515]:
velocity_df = clean_df[
    ["video_id", "trending_date", "views", "likes", "comment_count"]
].copy()

velocity_df = velocity_df.sort_values(
    ["video_id", "trending_date"]
).reset_index(drop=True)

velocity_df["previous_views"] = (
    velocity_df.groupby("video_id")["views"].shift(1)
)

velocity_df["view_growth"] = (
    velocity_df["views"] - velocity_df["previous_views"]
)

velocity_df["view_growth_pct"] = (
    velocity_df["view_growth"] /
    velocity_df["previous_views"] * 100
)

velocity_df["view_velocity"] = (
    velocity_df["view_growth_pct"] / 100
)

velocity_df["engagement_rate"] = (
    (velocity_df["likes"] + velocity_df["comment_count"]) /
    velocity_df["views"] * 100
)

print(velocity_df.shape)
print(velocity_df.head(10))

(33089, 10)
  video_id trending_date   views  likes  comment_count  previous_views  \
0   #NAME?    2017-11-14   31052     36              2             NaN
1   #NAME?    2017-11-14   30659    180              3         31052.0
2   #NAME?    2017-11-14  743321   2570            294         30659.0
3   #NAME?    2017-11-15   28816    376             29        743321.0
4   #NAME?    2017-11-15   14529   1018             83         28816.0
5   #NAME?    2017-11-16   36956    442             29         14529.0
6   #NAME?    2017-11-16   20289   1221             95         36956.0
7   #NAME?    2017-11-16   12462     74              4         20289.0
8   #NAME?    2017-11-17   40104    170             12         12462.0
9   #NAME?    2017-11-18  228047   1395           1928         40104.0

   view_growth  view_growth_pct  view_velocity  engagement_rate
0          NaN              NaN            NaN         0.122375
1       -393.0        -1.265619      -0.012656         0.596888
2     712662.0      2324.478946      23.244789         0.385298
3    -714505.0       -96.123344      -0.961233         1.405469
4     -14287.0       -49.580094      -0.495801         7.577948
5      22427.0       154.360245       1.543602         1.274489
6     -16667.0       -45.099578      -0.450996         6.486273
7      -7827.0       -38.577554      -0.385776         0.625903
8      27642.0       221.810303       2.218103         0.453820
9     187943.0       468.639038       4.686390         1.457156

In [516]:
velocity_df = velocity_df[
    velocity_df["video_id"] != "#NAME?"
].reset_index(drop=True)

In [517]:
print(velocity_df["video_id"].unique()[:10])
print(velocity_df.shape)

<StringArray>
[    '#VALUE!', '-0N9r10xb_0', '-0WuM6ctLHg', '-0mcgX4ro7I', '-0neBEVK-3Y',
 '-0qWaHPYLRc', '-0qyoTYp7Lg', '-0rIUynSiX0', '-1Hd6cXt8pg', '-1LnwpleqLQ']
Length: 10, dtype: str
(32647, 10)

In [518]:
velocity_df = velocity_df[
    ~velocity_df["video_id"].isin(["#NAME?", "#VALUE!"])
].reset_index(drop=True)

In [519]:
print("Rows:", velocity_df.shape[0])
print("Invalid IDs:", velocity_df["video_id"].isin(["#NAME?", "#VALUE!"]).sum())
print(velocity_df["video_id"].head(10))

Rows: 32640
Invalid IDs: 0
0    -0N9r10xb_0
1    -0N9r10xb_0
2    -0WuM6ctLHg
3    -0WuM6ctLHg
4    -0WuM6ctLHg
5    -0mcgX4ro7I
6    -0mcgX4ro7I
7    -0neBEVK-3Y
8    -0neBEVK-3Y
9    -0neBEVK-3Y
Name: video_id, dtype: str

In [520]:
# Recalculate Step 11 metrics after removing invalid IDs

velocity_df = velocity_df.sort_values(
    ["video_id", "trending_date"]
).reset_index(drop=True)

velocity_df["previous_views"] = (
    velocity_df.groupby("video_id")["views"].shift(1)
)

velocity_df["view_growth"] = (
    velocity_df["views"] - velocity_df["previous_views"]
)

velocity_df["view_growth_pct"] = (
    velocity_df["view_growth"]
    / velocity_df["previous_views"]
) * 100

velocity_df["view_velocity"] = (
    velocity_df["view_growth_pct"] / 100
)

velocity_df["engagement_rate"] = (
    (velocity_df["likes"] + velocity_df["comment_count"])
    / velocity_df["views"]
) * 100

print(velocity_df.shape)
print(velocity_df.head(10))

(32640, 10)
      video_id trending_date   views  likes  comment_count  previous_views  \
0  -0N9r10xb_0    2017-11-19   71064   1061             16             NaN
1  -0N9r10xb_0    2017-11-20  133438   1381             39         71064.0
2  -0WuM6ctLHg    2018-02-11  179951   3076             82             NaN
3  -0WuM6ctLHg    2018-02-12  310078   3878             94        179951.0
4  -0WuM6ctLHg    2018-02-13  333432   4086             96        310078.0
5  -0mcgX4ro7I    2018-03-16  188429    983             60             NaN
6  -0mcgX4ro7I    2018-03-17  245666   1169             79        188429.0
7  -0neBEVK-3Y    2018-02-20  343635    879              0             NaN
8  -0neBEVK-3Y    2018-02-21  607293   1300              0        343635.0
9  -0neBEVK-3Y    2018-02-22  699595   1403              0        607293.0

   view_growth  view_growth_pct  view_velocity  engagement_rate
0          NaN              NaN            NaN         1.515535
1      62374.0        87.771586       0.877716         1.064165
2          NaN              NaN            NaN         1.754922
3     130127.0        72.312463       0.723125         1.280968
4      23354.0         7.531653       0.075317         1.254229
5          NaN              NaN            NaN         0.553524
6      57237.0        30.375898       0.303759         0.508007
7          NaN              NaN            NaN         0.255795
8     263658.0        76.726177       0.767262         0.214065
9      92302.0        15.198924       0.151989         0.200545

In [521]:
print(velocity_df["video_id"].isin(["#NAME?", "#VALUE!"]).sum())
print(velocity_df["trending_date"].min())
print(velocity_df["trending_date"].max())

0
2017-11-14 00:00:00
2018-06-14 00:00:00

In [523]:
from pathlib import Path

Path("data/processed").mkdir(parents=True, exist_ok=True)

In [524]:
velocity_df.to_csv(
    "data/processed/velocity_df.csv",
    index=False
)

In [525]:
velocity_df["growth_score"] = (
    velocity_df["view_velocity"].rank(pct=True) * 100
)

velocity_df["engagement_score"] = (
    velocity_df["engagement_rate"].rank(pct=True) * 100
)

In [526]:
velocity_df["trend_velocity_score"] = (
    0.7 * velocity_df["growth_score"]
    + 0.3 * velocity_df["engagement_score"]
)

In [528]:
velocity_df["trend_status"] = pd.cut(
    velocity_df["trend_velocity_score"],
    bins=[-1, 40, 60, 80, 100],
    labels=["Normal", "Growing", "Hot", "Viral"]
)

In [529]:
print(
    velocity_df[
        [
            "video_id",
            "view_velocity",
            "engagement_rate",
            "growth_score",
            "engagement_score",
            "trend_velocity_score",
            "trend_status"
        ]
    ].head(10)
)

      video_id  view_velocity  engagement_rate  growth_score  \
0  -0N9r10xb_0            NaN         1.515535           NaN
1  -0N9r10xb_0       0.877716         1.064165     87.089073
2  -0WuM6ctLHg            NaN         1.754922           NaN
3  -0WuM6ctLHg       0.723125         1.280968     82.393633
4  -0WuM6ctLHg       0.075317         1.254229     13.045608
5  -0mcgX4ro7I            NaN         0.553524           NaN
6  -0mcgX4ro7I       0.303759         0.508007     54.037343
7  -0neBEVK-3Y            NaN         0.255795           NaN
8  -0neBEVK-3Y       0.767262         0.214065     83.979186
9  -0neBEVK-3Y       0.151989         0.200545     29.898990

   engagement_score  trend_velocity_score trend_status
0         58.624387                   NaN          NaN
1         49.905025             75.933858          Hot
2         62.058824                   NaN          NaN
3         54.788603             74.112124          Hot
4         54.270833             25.413175       Normal
5         29.460784                   NaN          NaN
6         26.580882             45.800405      Growing
7         10.168505                   NaN          NaN
8          7.585784             61.061165          Hot
9          6.767770             22.959624       Normal

In [532]:
print(velocity_df["trend_status"].value_counts())

trend_status
Normal     5666
Growing    4821
Hot        4389
Viral      1459
Name: count, dtype: int64

In [533]:
velocity_df.to_csv(
    "data/processed/velocity_df.csv",
    index=False
)

In [534]:
velocity_df["velocity_percentile"] = (
    velocity_df["view_velocity"].rank(pct=True) * 100
)

velocity_df["engagement_percentile"] = (
    velocity_df["engagement_rate"].rank(pct=True) * 100
)

In [535]:
velocity_df["growth_score"] = velocity_df["velocity_percentile"]

velocity_df["engagement_score"] = velocity_df["engagement_percentile"]

velocity_df["emerging_trend_score"] = (
    0.6 * velocity_df["growth_score"]
    + 0.4 * velocity_df["engagement_score"]
)

In [536]:
velocity_df["emerging_status"] = pd.cut(
    velocity_df["emerging_trend_score"],
    bins=[-1, 40, 60, 80, 100],
    labels=["Normal", "Growing", "Emerging", "Hot"]
)

In [537]:
velocity_df["trend_alert"] = velocity_df["emerging_status"].isin(
    ["Emerging", "Hot"]
)

In [538]:
print(
    velocity_df[
        [
            "video_id",
            "emerging_trend_score",
            "emerging_status",
            "trend_alert"
        ]
    ].head(10)
)

      video_id  emerging_trend_score emerging_status  trend_alert
0  -0N9r10xb_0                   NaN             NaN        False
1  -0N9r10xb_0             72.215453        Emerging         True
2  -0WuM6ctLHg                   NaN             NaN        False
3  -0WuM6ctLHg             71.351621        Emerging         True
4  -0WuM6ctLHg             29.535698          Normal        False
5  -0mcgX4ro7I                   NaN             NaN        False
6  -0mcgX4ro7I             43.054759         Growing        False
7  -0neBEVK-3Y                   NaN             NaN        False
8  -0neBEVK-3Y             53.421825         Growing        False
9  -0neBEVK-3Y             20.646502          Normal        False

In [539]:
print(
    velocity_df[
        [
            "video_id",
            "emerging_trend_score",
            "emerging_status",
            "trend_alert"
        ]
    ].head(10)
)

      video_id  emerging_trend_score emerging_status  trend_alert
0  -0N9r10xb_0                   NaN             NaN        False
1  -0N9r10xb_0             72.215453        Emerging         True
2  -0WuM6ctLHg                   NaN             NaN        False
3  -0WuM6ctLHg             71.351621        Emerging         True
4  -0WuM6ctLHg             29.535698          Normal        False
5  -0mcgX4ro7I                   NaN             NaN        False
6  -0mcgX4ro7I             43.054759         Growing        False
7  -0neBEVK-3Y                   NaN             NaN        False
8  -0neBEVK-3Y             53.421825         Growing        False
9  -0neBEVK-3Y             20.646502          Normal        False

In [540]:
print(velocity_df["emerging_status"].value_counts())

emerging_status
Growing     5842
Normal      5077
Emerging    4181
Hot         1235
Name: count, dtype: int64

In [541]:
velocity_df.to_csv(
    "data/processed/velocity_df.csv",
    index=False
)

In [542]:
# First date each video appeared
first_date = (
    velocity_df.groupby("video_id")["trending_date"]
    .min()
    .reset_index()
    .rename(columns={"trending_date": "first_trending_date"})
)

# Merge first date back
velocity_df = velocity_df.merge(
    first_date,
    on="video_id",
    how="left"
)

In [543]:
velocity_df["days_since_first_trending"] = (
    velocity_df["trending_date"]
    - velocity_df["first_trending_date"]
).dt.days

In [544]:
emerging_dates = (
    velocity_df[
        velocity_df["emerging_status"].isin(["Emerging", "Hot"])
    ]
    .groupby("video_id")["trending_date"]
    .min()
    .reset_index()
    .rename(columns={"trending_date": "emerging_date"})
)

In [545]:
velocity_df = velocity_df.merge(
    emerging_dates,
    on="video_id",
    how="left"
)

velocity_df["time_to_trend_days"] = (
    velocity_df["emerging_date"]
    - velocity_df["first_trending_date"]
).dt.days

In [548]:
print(
    velocity_df[
        ["video_id", "first_trending_date",
         "emerging_date", "time_to_trend_days"]
    ].head(10)
)

      video_id first_trending_date emerging_date  time_to_trend_days
0  -0N9r10xb_0          2017-11-19    2017-11-20                 1.0
1  -0N9r10xb_0          2017-11-19    2017-11-20                 1.0
2  -0WuM6ctLHg          2018-02-11    2018-02-12                 1.0
3  -0WuM6ctLHg          2018-02-11    2018-02-12                 1.0
4  -0WuM6ctLHg          2018-02-11    2018-02-12                 1.0
5  -0mcgX4ro7I          2018-03-16           NaT                 NaN
6  -0mcgX4ro7I          2018-03-16           NaT                 NaN
7  -0neBEVK-3Y          2018-02-20           NaT                 NaN
8  -0neBEVK-3Y          2018-02-20           NaT                 NaN
9  -0neBEVK-3Y          2018-02-20           NaT                 NaN

In [549]:
time_to_trend_df = velocity_df[
    velocity_df["time_to_trend_days"].notna()
].copy()

print(time_to_trend_df[
    ["video_id", "time_to_trend_days"]
].head(10))

       video_id  time_to_trend_days
0   -0N9r10xb_0                 1.0
1   -0N9r10xb_0                 1.0
2   -0WuM6ctLHg                 1.0
3   -0WuM6ctLHg                 1.0
4   -0WuM6ctLHg                 1.0
23  -20cEGjbyGY                 1.0
24  -20cEGjbyGY                 1.0
25  -20cEGjbyGY                 1.0
31  -2qGKp-Jp8c                 1.0
32  -2qGKp-Jp8c                 1.0

In [550]:
print(
    time_to_trend_df["time_to_trend_days"].describe()
)

count    15086.000000
mean         1.019422
std          0.167911
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: time_to_trend_days, dtype: float64

In [551]:
time_to_trend_df.to_csv(
    "data/processed/time_to_trend.csv",
    index=False
)

In [552]:
emerging_trends = velocity_df[
    [
        "video_id",
        "trending_date",
        "views",
        "view_growth",
        "view_growth_pct",
        "view_velocity",
        "engagement_rate",
        "emerging_trend_score",
        "emerging_status",
        "trend_alert"
    ]
].copy()

In [553]:
print(emerging_trends.shape)
print(emerging_trends.head())
print(emerging_trends.columns.tolist())

(32640, 10)
      video_id trending_date   views  view_growth  view_growth_pct  \
0  -0N9r10xb_0    2017-11-19   71064          NaN              NaN
1  -0N9r10xb_0    2017-11-20  133438      62374.0        87.771586
2  -0WuM6ctLHg    2018-02-11  179951          NaN              NaN
3  -0WuM6ctLHg    2018-02-12  310078     130127.0        72.312463
4  -0WuM6ctLHg    2018-02-13  333432      23354.0         7.531653

   view_velocity  engagement_rate  emerging_trend_score emerging_status  \
0            NaN         1.515535                   NaN             NaN
1       0.877716         1.064165             72.215453        Emerging
2            NaN         1.754922                   NaN             NaN
3       0.723125         1.280968             71.351621        Emerging
4       0.075317         1.254229             29.535698          Normal

   trend_alert
0        False
1         True
2        False
3         True
4        False
['video_id', 'trending_date', 'views', 'view_growth', 'view_growth_pct', 'view_velocity', 'engagement_rate', 'emerging_trend_score', 'emerging_status', 'trend_alert']

In [554]:
emerging_trends = emerging_trends.sort_values(
    "emerging_trend_score",
    ascending=False
).reset_index(drop=True)

In [555]:
print(
    emerging_trends[
        [
            "video_id",
            "emerging_trend_score",
            "emerging_status",
            "view_growth_pct",
            "engagement_rate",
            "trend_alert"
        ]
    ].head(10)
)

      video_id  emerging_trend_score emerging_status  view_growth_pct  \
0  ZqG90jzu2QE             97.727482             Hot       257.806689
1  2s4GMLkTNv0             97.516995             Hot       224.774080
2  RiyEX5gtyVY             96.877036             Hot       173.222479
3  3VCMKI3vbX8             96.733846             Hot       232.780905
4  tHmAPWOo2jY             96.714974             Hot       294.659423
5  s0_G-Kk6-Yg             96.331612             Hot       262.542420
6  BHHIlEv_YdY             96.235325             Hot       156.060584
7  AaK8pFtg1BI             96.210653             Hot       222.893677
8  Xr2UE5SQCIU             96.124529             Hot       151.740076
9  u_nrjjXlO1M             95.870182             Hot       537.222332

   engagement_rate  trend_alert
0        10.229691         True
1        10.507163         True
2        11.702701         True
3         8.836303         True
4         8.023418         True
5         7.834772         True
6        11.235672         True
7         8.172399         True
8        11.259155         True
9         6.632359         True

In [556]:
emerging_trends.to_csv(
    "data/processed/emerging_trends.csv",
    index=False
)

In [557]:
print("Emerging trends table saved successfully!")

Emerging trends table saved successfully!

In [558]:
velocity_df["view_velocity"] = pd.to_numeric(
    velocity_df["view_velocity"],
    errors="coerce"
)

In [559]:
print(velocity_df["view_velocity"].dtype)

float64

In [560]:
print(velocity_df["view_velocity"].isna().sum())

16305

In [561]:
print(velocity_df["view_velocity"].isna().sum())

16305

In [562]:
print(velocity_df["view_velocity"].describe())

count    16335.000000
mean         0.460471
std          0.623440
min         -0.644530
25%          0.129229
50%          0.270347
75%          0.567567
max         14.985988
Name: view_velocity, dtype: float64

In [563]:
print(velocity_df["view_velocity"].head(20).tolist())

[nan, 0.8777158617584149, nan, 0.7231246283710565, 0.07531653325937344, nan, 0.3037589755292444, nan, 0.7672617748483129, 0.15198923748503607, 0.041629800098628496, 0.01370624342167557, nan, nan, 1.4478134804123335, 0.25754716628614777, nan, nan, nan, 0.6373370302637013]

In [564]:
velocity_df["view_velocity"] = pd.to_numeric(
    velocity_df["view_velocity"],
    errors="coerce"
)

In [565]:
velocity_df.to_csv(
    "data/processed/velocity_df.csv",
    index=False
)

In [566]:
emerging_trends["view_velocity"] = pd.to_numeric(
    emerging_trends["view_velocity"],
    errors="coerce"
)

emerging_trends.to_csv(
    "data/processed/emerging_trends.csv",
    index=False
)